# Copyright (c) 2026 Jorge Abraham Mendieta.
# Computational Substrate Theory. Todos los derechos reservados.

# MQTT ACL — Zero-Trust por identidad de usuario (%u)
# Formato: tenant_id_node_id

# Denegar acceso anónimo completamente.
user anonymous
topic read #
topic write #

# Cada usuario autenticado accede SOLO a su subárbol.
user %u
topic read  fleet/%u/#
topic write fleet/%u/#

# El servidor Fleet Manager tiene acceso global de escritura
# para publicar OTA y alertas a todos los nodos.
user fleet_server
topic read  fleet/#
topic write fleet/#
